### ISSUE TITLE
Mobile styling

### ISSUE THREAD

**Issue by LKian** [nishad10/utacsec#16]
On the "/officers" page, adjust the mobile styling.  The profile image is awkwardly narrow at 605px.  It should probably be above the officer bio text.
```
.ui.fluid.left.aligned.container {
flex-direction: column;
}
```
parent of .ui.card should have the width of 17em removed under 801px.  Add that specific styling to the desktop view.

**Comment by nishad10** [comment]
Hey nice spot, I will work on this as I get time, in the meantime if you want you can take this up and make a pr for it if you can.
